### ISSUE TITLE
[Bug] Cannot run sync - Invalid sync pairs registry

### ISSUE THREAD

**Issue by hartmark** [FilenCloudDienste/filen-cli#219]
**Describe the bug**
I'm running latest filen-cli and I'm trying to get the sync-command working, but I get an error message.

**To Reproduce**
`$ filen-cli sync
`
`Invalid sync pairs registry! Needs to be of type: {local: string, remote: string, syncMode: string, alias?: string, disableLocalTrash?: boolean, ignore?: string[]}[]`

`% cat /home/markus/.config/filen-cli/syncPairs.json`
```
{
  "local": "~/Documents",
  "remote": "/Documents",
  "syncMode": "twoWay"
}

```

**Expected behavior**
I want the sync to work

**Logs/Screenshots**
```
2024-12-07 00:18:43.300       Filen CLI v0.0.24
2024-12-07 00:18:43.300       > /usr/bin/filen-cli /snapshot/filen-cli/dist/bundle.js sync --log-file run.log
2024-12-07 00:18:42.576 [LOG] Filen CLI v0.0.24
2024-12-07 00:18:42.579 [LOG] Checked for updates not long ago, not checking again
2024-12-07 00:18:43.135 [LOG] Logging in as mail@hartmark.se (using saved credentials)
2024-12-07 00:18:43.300 [ERR] Invalid sync pairs registry! Needs to be of type: {local: string, remote: string, syncMode: string, alias?: string, disableLocalTrash?: boolean, ignore?: string[]}[]
```

**System (please complete the following information):**
- **Filen CLI version:** v0.0.24
- which build of the CLI you're using x64
- OS: Arch Linux

**Comment by JupiterPi** [comment]
By looking at it quickly, I think the issue is that your file actually contains JSON of the type `{local, remote, syncMode}` rather than `{...}[]` (i. e. the single sync pair needs to be enclosed in an array). Obviously, it would be nice if it worked either way. I'll have a closer look and implement a fix as soon as I can.

**Comment by hartmark** [comment]
I haven't seen that kind of syntax for json format before.

Now when I'm running sync I get cycleLocalSmokeTestFailed instead.

Masked my email and uuids (don't know if they are sensitive information)

```
% filen-cli --verbose sync
Filen CLI v0.0.24
Checked for updates not long ago, not checking again
Logging in as ***** (using saved credentials)
Syncing ~/Documents to /Documents (twoWay)...
Transferring files [========================================] 100% | ETA: 0s | 0 / 0{
  "type": "cycleLocalSmokeTestFailed",
  "syncPair": {
    "name": "~/Documents:/Documents",
    "uuid": "c*****1",
    "localPath": "~/Documents",
    "remotePath": "/Documents",
    "remoteParentUUID": "9****e",
    "mode": "twoWay",
    "excludeDotFiles": false,
    "paused": false,
    "localTrashDisabled": false
  }
}

```

**Comment by JupiterPi** [comment]
`cycleLocalSmokeTestFailed` means that the local path could not be found, because the CLI did not understand the meaning of `~` as the home path and interpreted it literally. This is fixed in [v0.0.26](https://github.com/FilenCloudDienste/filen-cli/releases/tag/v0.0.26), and `syncPairs.json` now also accepts a single JSON object instead of an array (like your original listing). Thanks for your feedback!

**Comment by hartmark** [comment]
Cool, I'll try out the updated version and report back if I still have issues.

I think the error needs to be more user friendly "cycleLocalSmokeTestFailed" meaning path not found is not super clear what the error is.

**Comment by JupiterPi** [comment]
Yes, that's true.
